[package]
name    = "bathbot"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[build-dependencies]
bindgen = "0.53"
cc      = { version = "1.0", features = ["parallel"] }

[dependencies]
chrono       = "0.4"
diesel       = { version = "1.4", features = ["mysql", "chrono", "r2d2"] }
dotenv       = "0.15"
fern         = { version = "0.6", features = ["colored"] }
image        = "0.23"
itertools    = "0.9"
log          = "0.4"
markov       = "1.0"
num-format   = "0.4"
rand         = "0.7"
rayon        = "1.3"
regex        = "1.3"
reqwest      = { version = "0.10", features = ["cookies"] }
# rosu         = "0.1.3"
rosu = { path = "../rosu" }
tokio        = { version = "0.2.13", features = ["full"] }
scraper      = "0.11"
serde        = "1.0"
serde_derive = "1.0"
serde_json   = "1.0"
# serenity     = { version = "0.8", features = ["cache", "client", "framework", "standard_framework", "rustls_backend"] }
strfmt       = "0.1.6"
sysinfo      = "0.11"

[dependencies.serenity]
git      = "https://github.com/Lakelezz/serenity/"
version  = "0.8.1"
branch   = "await"
features = ["cache", "client", "framework", "standard_framework", "rustls_backend", "collector"]
