[package]
name = "bathbot"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[dependencies]
rosu = "0.1.1"
roppai = { path = "../roppai" }
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
serenity = { version = "0.8", features = ["cache", "framework", "standard_framework", "rustls_backend"] }
num-format = "0.4"
chrono = "0.4"
reqwest = { version = "0.10", features = ["cookies"] }
itertools = "0.8"
scraper = "0.11"
diesel = { version = "1.4", features = ["mysql", "chrono", "r2d2"] }
image = "0.23"
regex = "1.3"
white_rabbit = "0.1"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"